# Generated by Django 3.0.1 on 2019-12-20 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employ_id', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('office_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.timezone)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=254)),
                ('checkout', models.DateTimeField()),
                ('time_slot', models.DateTimeField()),
            ],
        ),
    ]
