# Generated by Django 3.0.1 on 2019-12-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeInfo',
        ),
    ]
