# Generated by Django 3.0.1 on 2019-12-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_delete_employeeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('employ_id', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('office_address', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
