# Generated by Django 3.0.1 on 2019-12-20 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0003_employeeinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfo',
            name='employ_id',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='password',
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
