# Generated by Django 3.0.1 on 2019-12-20 11:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20191220_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='visitorinfo',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
