# Generated by Django 3.0.1 on 2019-12-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20191227_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorinfo',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='visitorinfo',
            name='time_slot',
        ),
    ]
