# Generated by Django 3.0.1 on 2019-12-27 09:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_auto_20191227_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorinfo',
            name='date_time',
        ),
        migrations.AlterField(
            model_name='visitorinfo',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
