# Generated by Django 3.0.1 on 2019-12-27 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_auto_20191227_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorinfo',
            name='host',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='firstapp.EmployeeInfo'),
        ),
    ]
