# Generated by Django 3.0.1 on 2019-12-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_auto_20191227_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorinfo',
            name='host',
        ),
    ]
