# Generated by Django 3.0.1 on 2019-12-27 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_remove_visitorinfo_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorinfo',
            name='host',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='firstapp.EmployeeInfo'),
            preserve_default=False,
        ),
    ]
