# Generated by Django 3.0.1 on 2019-12-31 11:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0016_remove_visitorinfo_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorinfo',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
