# Generated by Django 3.0.1 on 2020-01-02 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0018_visitorinfo_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorinfo',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.EmployeeInfo'),
        ),
    ]
