# Generated by Django 3.0.1 on 2020-01-03 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0019_auto_20200102_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorinfo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
