# Generated by Django 3.0.1 on 2020-01-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0020_visitorinfo_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorinfo',
            name='checkout',
            field=models.DateTimeField(null=True),
        ),
    ]
